<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <LangVersion>8.0</LangVersion>
    <Nullable>enable</Nullable>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>AMS2LeagueClient</AssemblyName>
    <RootNamespace>AMS2LeagueClient</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AMS2LeagueClient.Core\AMS2LeagueClient.Core.csproj" />
  </ItemGroup>
</Project>
